# This file was *autogenerated* from the file thesis.sage.
from sage.all_cmdline import *   # import sage library
## This file (thesis.sage) was *autogenerated* from the file thesis.tex.
import sagetex
_st_ = sagetex.SageTeXProcessor('thesis')
_st_.endofdoc()
